In [14]:
import math

start = [0,0]
stop = [0,0]
moves = ['UP 5', 'DOWN 3', 'LEFT 3', 'RIGHT 2']

for i in moves:
    j = i.split()[0]
    k = int(i.split()[1])
    if j == 'UP':
        stop[1] += k
    elif j == 'DOWN':
        stop[1] -= k
    elif j == 'RIGHT':
        stop[0] += k
    elif j == 'LEFT':
        stop[0] -= k

print('current position is : ', stop)

d = math.sqrt(((stop[0]-start[0])**2 + (stop[1]-start[1])**2))
d = round(d,2)
print(f'distance from initial prosition to current position is {d} units')

current position is :  [-1, 2]
distance from initial prosition to current position is 2.24 units


In [20]:
l = [1,2,3,4,5,6,7,8,9,10]   #sorted list to search for data

In [21]:
# search function to search data inside list
def search(l,n):
    for i in range(len(l)):
        if l[i] == n:
            postion = i
            print(f'The value {n} is at position {i} inside the list')
            break
    else:
        print(f'The value {n} is not inside the list')

In [22]:
# searching for 8 inside list 'l' using search function defined above

search(l, 8)

The value 8 is at position 7 inside the list


In [23]:
# searching for 100 inside list 'l' using search function defined above

search(l, 100)

The value 100 is not inside the list


In [18]:
# assume after 7 PM and till 7 AM it will be dark

import time

curr_time = time.asctime()
if int(curr_time[11:13]) >= 19 or int(curr_time[11:13]) <= 6:
    print('Its dark outside')
else:
    print('Its not dark outside')

Its not dark outside


In [19]:
from math import radians, sin, cos, acos

print("Input coordinates of two points:")
slat = radians(float(input("Starting latitude: ")))
slon = radians(float(input("Starting longitude: ")))
elat = radians(float(input("ending latitude: ")))
elon = radians(float(input("Ending longitude: ")))

dist = round(6371.01 * acos(sin(slat)*sin(elat) + cos(slat)*cos(elat)*cos(slon - elon)),2)
print(f"The distance is {dist} km.")

Input coordinates of two points:
Starting latitude: 12
Starting longitude: 77
ending latitude: 9
Ending longitude: 76
The distance is 351.04 km.


In [24]:
class Account:
    def __init__(self, name, balance, min_balance, password = 'welcome'):
        self.name = name
        self.balance = balance
        self.min_balance = min_balance
        self.password = password
        
    def credit(self, amount):
        x = input('Enter the password: \n')
        if x == self.password:
            self.balance += amount
            print(f'Deposit successful. You account balance is {self.balance}')
        else:
            print('Sorry! wrong password. Please retry with right password.')
    def withdrawal(self, amount):
        x = input('Enter the password: \n')
        if x == self.password:
            if amount <= self.balance:
                self.balance -= amount
                print(f'Withdrawal successful. You account balance is {self.balance}')
            else:
                print('Sorry! Insufficient balance.')
        else:
            print('Sorry! wrong password. Please retry with right password.')
    def password_change(self):
        p = input('Enter the new password: \n')
        self.password = p

In [25]:
sre = Account('Sreeraj', 100, 0)

In [26]:
sre.password_change()

Enter the new password: 
abcd1


In [27]:
sre.credit(10)

Enter the password: 
10
Sorry! wrong password. Please retry with right password.


In [28]:
sre.credit(10)

Enter the password: 
abcd1
Deposit successful. You account balance is 110


In [29]:
sre.balance

110

In [30]:
# defining a functon should run with upper limit and lower limit numbers, 
# will give the numbers which are divisible by 7 but are not a multiple of 5 as output

def find_numbers(upper,lower):
    l = []
    for i in range(upper,lower+1):
        if i%7 == 0 and i%5 != 0:
            l.append(str(i))
    print(', '.join(l))

In [31]:
find_numbers(2000, 3200)

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


In [34]:
def factorial(n):
    if n==0:
        return 1
    else:
        return n*factorial(n-1)

In [35]:
factorial(5)

120

In [36]:
import math

def number_out():
    l = input('Enter the numbers seperated by comma: \n').split(',')
    o = []
    for i in l:
        o.append(str(int(math.sqrt(10*int(i)/3))))
    print(','.join(o))

In [37]:
number_out()

Enter the numbers seperated by comma: 
100,150,180
18,22,24


In [38]:
import numpy as np

r = int(input('Enter the number of rows: \n'))
c = int(input('Enter the number of columns: \n'))
l =[]
for i in range(r):
    l.append([])

for i in range(r):
    for j in range(c):
        l[i].append(i*j)
a = np.array(l)
print(a)
print(type(a))

Enter the number of rows: 
3
Enter the number of columns: 
5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]
<class 'numpy.ndarray'>


In [39]:
def word_sort():
    l = input('Enter the words separated by comma: \n').split(',')
    l.sort()
    print(','.join(l))

In [40]:
word_sort()

Enter the words separated by comma: 
without, hello, bag, world
 bag, hello, world,without


In [41]:
def caps():
    s = input('Enter the sentance: \n')
    print(s.upper())

In [42]:
caps()

Enter the sentance: 
Hello world
HELLO WORLD


In [43]:
def word_order():
    l = input('Enter the words seperated by space: \n').split()
    l = list(set(l))
    l.sort()
    print(' '.join(l))

In [44]:
word_order()

Enter the words seperated by space: 
hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


In [45]:
#binary to decimal converter (b should be given as a string)

def binary_to_decimal(b):
    l = list(b)
    d = 0
    for i in range(len(b)):
        x = l.pop()
        if x == '1':
            d += pow(2,i)
    return(d)

# function to take binary numbers and output multiples of 5

def div_check():
    m = input('Enter 4 binary numbers seperated by comma: \n').split(',')
    a = list(map(binary_to_decimal, m))
    for i in a:
        if i%5 == 0:
            print(m[a.index(i)])

In [46]:
div_check()

Enter 4 binary numbers seperated by comma: 
0100,0011,1010,1001
1010


In [47]:
def case_check():
    s = input('Enter the sentence: \n')
    u = 0
    l = 0
    for i in s:
        if i.isupper():
            u += 1
        elif i.islower():
            l += 1
    print(f'UPPER CASE : {u} & LOWER CASE : {l}')

In [48]:
case_check()

Enter the sentence: 
Hello world!
UPPER CASE : 1 & LOWER CASE : 9


In [49]:
import math

l = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [50]:
math.fsum(l)  # fsum function in math module

1.0

In [51]:
sum(l)  # sum function

0.9999999999999999