## Project - Pharma

Maple Leaves Ltd is a start-up company which makes herbs from different types of plants and its leaves. Currently the system they use to classify the trees which they import in a batch is quite manual. A labourer from his experience decides the leaf type and subtype of plant family. They have asked us to automate this process and remove any manual intervention from this process.

Objective: To classify the plant leaves by various classifiers from different metrics of the leaves and to choose the best classifier for future reference.

Implementation:

1) Import the train and test csv.

2) Import the required classification libraries along with pandas, numpy, seaborn etc

3) Then import the classifiers from them (Randomforest, SVM, NaiveBayes, DecisionTrees)

4) After this create a function to encode the labels of the strings given in the dataset

5) You can do the above step using label encoder. With this you are creating some labels from train set as test set. The test set we imported is for testing the best classifier accuracy once we choose it

6) Then extract the values from train set by stratifying them and dividing it into 80:20 ratio

7) Now your X train, X test, Y train, Y test are ready.

8) We currently don’t know which is the best classifier on the dataset. So, we apply all 4 of them.

9) Create the classifiers class and initialize all the respective classifiers

10) Then run the X train & X test datasets through classifiers calculating the log loss and accuracy of the result

11) Choose the classifier which has the best accuracy

12) Then try to predict the result on the import test.csv dataset

1) Import the train and test csv.

In [2]:
train = pd.read_csv(r'D:\E\Courses\Edureka\Assignments\Dataset\Projects\train.csv')
test = pd.read_csv(r'D:\E\Courses\Edureka\Assignments\Dataset\Projects\test.csv')

In [3]:
print(train.shape)
train.head()

(990, 194)


id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   

    margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0  ...   0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 194 columns]

In [4]:
print(test.shape)
test.head()

(594, 193)


id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2   9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836   0.000000   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000   0.000000   0.006836   0.001953   
2      0.0  0.011719  ...   0.128910   0.000000   0.000977   0.000000   
3      0.0  0.003906  ...   0.012695   0.015625   0.002930   0.036133   
4      0.0  0.005859  ...   0.000000   0.042969   0.016602   0.010742   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 193 columns]

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Columns: 194 entries, id to texture64
dtypes: float64(192), int64(1), object(1)
memory usage: 1.5+ MB


In [14]:
train.describe()

id     margin1     margin2     margin3     margin4  \
count   990.000000  990.000000  990.000000  990.000000  990.000000   
mean    799.595960    0.017412    0.028539    0.031988    0.023280   
std     452.477568    0.019739    0.038855    0.025847    0.028411   
min       1.000000    0.000000    0.000000    0.000000    0.000000   
25%     415.250000    0.001953    0.001953    0.013672    0.005859   
50%     802.500000    0.009766    0.011719    0.025391    0.013672   
75%    1195.500000    0.025391    0.041016    0.044922    0.029297   
max    1584.000000    0.087891    0.205080    0.156250    0.169920   

          margin5     margin6     margin7     margin8     margin9  ...  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  ...   
mean     0.014264    0.038579    0.019202    0.001083    0.007167  ...   
std      0.018390    0.052030    0.017511    0.002743    0.008933  ...   
min      0.000000    0.000000    0.000000    0.000000    0.000000  ...   
25%      0.001953    0.000000    0.005859    0.000000    0.001953  ...   
50%      0.007812    0.015625    0.015625    0.000000    0.005859  ...   
75%      0.017578    0.056153    0.029297    0.000000    0.007812  ...   
max      0.111330    0.310550    0.091797    0.031250    0.076172  ...   

        texture55   texture56   texture57   texture58   texture59   texture60  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000   
mean     0.036501    0.005024    0.015944    0.011586    0.016108    0.014017   
std      0.063403    0.019321    0.023214    0.025040    0.015335    0.060151   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000977    0.000000    0.004883    0.000000   
50%      0.004883    0.000000    0.005859    0.000977    0.012695    0.000000   
75%      0.043701    0.000000    0.022217    0.009766    0.021484    0.000000   
max      0.429690    0.202150    0.172850    0.200200    0.106450    0.578130   

        texture61   texture62   texture63   texture64  
count  990.000000  990.000000  990.000000  990.000000  
mean     0.002688    0.020291    0.008989    0.019420  
std      0.011415    0.039040    0.013791    0.022768  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000977  
50%      0.000000    0.003906    0.002930    0.011719  
75%      0.000000    0.023438    0.012695    0.029297  
max      0.151370    0.375980    0.086914    0.141600  

[8 rows x 193 columns]

In [13]:
pd.DataFrame(train.isna().sum()).iloc[:,0].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [5]:
train.species.unique()

array(['Acer_Opalus', 'Pterocarya_Stenoptera', 'Quercus_Hartwissiana',
       'Tilia_Tomentosa', 'Quercus_Variabilis', 'Magnolia_Salicifolia',
       'Quercus_Canariensis', 'Quercus_Rubra', 'Quercus_Brantii',
       'Salix_Fragilis', 'Zelkova_Serrata', 'Betula_Austrosinensis',
       'Quercus_Pontica', 'Quercus_Afares', 'Quercus_Coccifera',
       'Fagus_Sylvatica', 'Phildelphus', 'Acer_Palmatum',
       'Quercus_Pubescens', 'Populus_Adenopoda', 'Quercus_Trojana',
       'Alnus_Sieboldiana', 'Quercus_Ilex', 'Arundinaria_Simonii',
       'Acer_Platanoids', 'Quercus_Phillyraeoides', 'Cornus_Chinensis',
       'Liriodendron_Tulipifera', 'Cytisus_Battandieri',
       'Rhododendron_x_Russellianum', 'Alnus_Rubra',
       'Eucalyptus_Glaucescens', 'Cercis_Siliquastrum',
       'Cotinus_Coggygria', 'Celtis_Koraiensis', 'Quercus_Crassifolia',
       'Quercus_Kewensis', 'Cornus_Controversa', 'Quercus_Pyrenaica',
       'Callicarpa_Bodinieri', 'Quercus_Alnifolia', 'Acer_Saccharinum',
       'Prun

In [24]:
len(list(train.species.unique()))

99

2) Import the required classification libraries along with pandas, numpy, seaborn etc

3) Then import the classifiers from them (Randomforest, SVM, NaiveBayes, DecisionTrees)

4) After this create a function to encode the labels of the strings given in the dataset

5) You can do the above step using label encoder. With this you are creating some labels from train set as test set. The test set we imported is for testing the best classifier accuracy once we choose it

6) Then extract the values from train set by stratifying them and dividing it into 80:20 ratio

7) Now your X train, X test, Y train, Y test are ready.

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [20]:
y = train.iloc[:,1].values
x = train.iloc[:,2:].values

In [22]:
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
y

array([ 3, 49, 65, 94, 84, 40, 54, 78, 53, 89, 98, 16, 74, 50, 58, 31, 43,
        4, 75, 44, 83, 84, 13, 66, 15,  6, 73, 22, 73, 31, 36, 27, 94, 88,
       12, 28, 21, 25, 20, 60, 84, 65, 69, 58, 23, 76, 18, 52, 54,  9, 48,
       47, 64, 81, 83, 36, 58, 21, 81, 20, 62, 88, 34, 92, 79, 82, 20, 32,
        4, 84, 36, 35, 72, 60, 71, 72, 52, 50, 54, 11, 51, 18, 47,  5,  8,
       37, 97, 20, 33,  1, 59,  1, 56,  1,  9, 57, 20, 79, 29, 16, 32, 54,
       93, 10, 46, 59, 84, 76, 15, 10, 15,  0, 69,  4, 51, 51, 94, 36, 39,
       62,  2, 24, 26, 35, 25, 87,  0, 55, 34, 38,  1, 45,  7, 93, 56, 38,
       21, 51, 75, 81, 74, 33, 20, 37,  9, 40, 60, 31, 83, 50, 71, 67, 30,
       66,  1, 43, 61, 23, 65, 84, 87, 46, 57, 16,  2, 28, 12, 96, 44, 76,
       29, 75, 41, 87, 67, 61, 30,  5, 12, 62,  3, 83, 81,  6, 85,  4, 37,
       57, 84, 39, 71, 61,  6, 76, 14, 31, 98, 40, 17, 51, 16, 42, 63, 86,
       37, 69, 86, 71, 80, 78, 14, 35, 25,  5, 39,  8,  9, 26, 44, 60, 13,
       14, 77, 13, 80, 87

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [28]:
len(x_train), len(x_test), len(y_train), len(y_test)

(792, 198, 792, 198)

8) We currently don’t know which is the best classifier on the dataset. So, we apply all 4 of them.

9) Create the classifiers class and initialize all the respective classifiers

10) Then run the X train & X test datasets through classifiers calculating the log loss and accuracy of the result

##### applying decesion tree classifier

In [29]:
dtc_model = DecisionTreeClassifier()
dtc_model.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [31]:
y_pred_dtc = dtc_model.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [33]:
confusion_matrix(y_test, y_pred_dtc)

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 2, 0],
       [0, 1, 0, ..., 0, 0, 1]], dtype=int64)

In [35]:
accuracy_dtc = accuracy_score(y_test, y_pred_dtc)
accuracy_dtc

0.5303030303030303

In [37]:
accuracy = {}
accuracy['dtc_model'] = accuracy_dtc

##### applying random forest classifier

In [38]:
rfc_model = RandomForestClassifier(n_estimators=10)
rfc_model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [40]:
y_pred_rfc = rfc_model.predict(x_test)

In [41]:
confusion_matrix(y_test, y_pred_rfc)

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [42]:
accuracy_score(y_test, y_pred_rfc)

0.8232323232323232

applying grid search to check if we can imprive rfc_model by changing estimators

In [47]:
from sklearn.model_selection import GridSearchCV

lst = list(range(1,26))
parameters = [{'n_estimators':lst}]

In [48]:
grid_search = GridSearchCV(estimator=rfc_model, param_grid=parameters, scoring='accuracy', n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)

In [49]:
best_accuracy = grid_search.best_score_
best_parameter = grid_search.best_params_

In [50]:
best_accuracy, best_parameter

(0.9343443993312635, {'n_estimators': 25})

In [51]:
rfc_model2 = RandomForestClassifier(n_estimators=25)
rfc_model2.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [53]:
y_pred_rfc2 = rfc_model2.predict(x_test)

In [54]:
confusion_matrix(y_test, y_pred_rfc2)

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 3, 0],
       [0, 0, 0, ..., 0, 0, 4]], dtype=int64)

In [55]:
accuracy_score(y_test, y_pred_rfc2)

0.9191919191919192

#### Applying Naive Base classifier

In [62]:
nbc_model = GaussianNB()
nbc_model.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [63]:
y_pred_nbc = nbc_model.predict(x_test)

In [64]:
confusion_matrix(y_test, y_pred_nbc)

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 2]], dtype=int64)

In [65]:
accuracy_score(y_test, y_pred_nbc)

0.4696969696969697

#### Applying SVM

In [66]:
svm_lin_model = SVC(kernel='linear')
svm_lin_model.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [68]:
y_pred_svm_lin = svm_lin_model.predict(x_test)

In [69]:
confusion_matrix(y_test, y_pred_svm_lin)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [70]:
accuracy_score(y_test, y_pred_svm_lin)

0.025252525252525252

In [71]:
# applying grid search to find which parameters are good for svm classifier

parameters = [{'C':[2,3,4,5,6,7], 'kernel':['sigmoid', 'rbf', 'poly']}]

grid_search = GridSearchCV(estimator=svm_lin_model, param_grid=parameters, scoring='accuracy', n_jobs=-1)

grid_search = grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


In [72]:
best_accuracy, best_parameters

(0.9204999601942522, {'C': 5, 'kernel': 'rbf'})

In [73]:
svm_rbf_model = SVC(kernel='rbf', C=5)
svm_rbf_model.fit(x_train, y_train)

SVC(C=5, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [75]:
y_pred_rbf = svm_rbf_model.predict(x_test)

In [76]:
confusion_matrix(y_test, y_pred_rbf)

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 3, 0],
       [0, 0, 0, ..., 0, 0, 3]], dtype=int64)

In [77]:
accuracy_score(y_test, y_pred_rbf)

0.9242424242424242

#### Best model is svm classifier with rbf kernel & then random forest classifier with estimator as 25

##### Predicting the output of given test data using svm classifier with rbf kernel

In [78]:
test.head(2)

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836        0.0   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000        0.0   0.006836   0.001953   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  

[2 rows x 193 columns]

In [81]:
test_ar = test.iloc[:,1:].values

In [83]:
y_pred_test = svm_rbf_model.predict(test_ar)

In [114]:
predict_df = pd.concat([test,pd.DataFrame(y_pred_test)], axis=1)
predict_df

id   margin1   margin2   margin3   margin4   margin5   margin6  \
0       4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625   
1       7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672   
2       9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000   
3      12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000   
4      13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000   
..    ...       ...       ...       ...       ...       ...       ...   
589  1576  0.000000  0.000000  0.003906  0.015625  0.041016  0.000000   
590  1577  0.000000  0.003906  0.003906  0.005859  0.017578  0.000000   
591  1579  0.017578  0.029297  0.015625  0.013672  0.003906  0.015625   
592  1580  0.013672  0.009766  0.060547  0.025391  0.035156  0.025391   
593  1583  0.000000  0.117190  0.000000  0.019531  0.000000  0.136720   

      margin7   margin8   margin9  ...  texture56  texture57  texture58  \
0    0.005859  0.000000  0.005859  ...   0.000000   0.015625   0.000977   
1    0.007812  0.000000  0.033203  ...   0.000000   0.006836   0.001953   
2    0.023438  0.000000  0.011719  ...   0.000000   0.000977   0.000000   
3    0.003906  0.000000  0.003906  ...   0.015625   0.002930   0.036133   
4    0.009766  0.000000  0.005859  ...   0.042969   0.016602   0.010742   
..        ...       ...       ...  ...        ...        ...        ...   
589  0.017578  0.000000  0.005859  ...   0.000000   0.004883   0.000000   
590  0.017578  0.005859  0.000000  ...   0.004883   0.004883   0.002930   
591  0.025391  0.000000  0.000000  ...   0.000000   0.028320   0.000000   
592  0.039062  0.000000  0.003906  ...   0.000000   0.000977   0.000000   
593  0.001953  0.005859  0.000000  ...   0.012695   0.016602   0.000977   

     texture59  texture60  texture61  texture62  texture63  texture64   0  
0     0.015625        0.0        0.0   0.000000   0.003906   0.053711  51  
1     0.013672        0.0        0.0   0.000977   0.037109   0.044922  50  
2     0.000000        0.0        0.0   0.015625   0.000000   0.000000   1  
3     0.013672        0.0        0.0   0.089844   0.000000   0.008789  19  
4     0.041016        0.0        0.0   0.007812   0.009766   0.007812  14  
..         ...        ...        ...        ...        ...        ...  ..  
589   0.003906        0.0        0.0   0.018555   0.000000   0.000977   1  
590   0.009766        0.0        0.0   0.090820   0.000000   0.016602  12  
591   0.001953        0.0        0.0   0.000000   0.042969   0.006836  54  
592   0.011719        0.0        0.0   0.000000   0.011719   0.018555  73  
593   0.004883        0.0        0.0   0.015625   0.000000   0.017578  15  

[594 rows x 194 columns]

In [115]:
predict_df = predict_df.rename(columns={0:'Group'})
predict_df.head(1)

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   

   margin8   margin9  ...  texture56  texture57  texture58  texture59  \
0      0.0  0.005859  ...        0.0   0.015625   0.000977   0.015625   

   texture60  texture61  texture62  texture63  texture64  Group  
0        0.0        0.0        0.0   0.003906   0.053711     51  

[1 rows x 194 columns]

In [116]:
map_df = pd.concat([pd.DataFrame(y), train.iloc[:,1]], axis=1)
map_df = map_df.rename(columns = {0:'Group'})
map_df.head(2)

Group                species
0      3            Acer_Opalus
1     49  Pterocarya_Stenoptera

In [121]:
predict_df = pd.merge(predict_df, map_df, how='outer', on='Group').drop_duplicates(subset=None, keep='first', inplace=False)
predict_df

id   margin1   margin2   margin3   margin4   margin5   margin6  \
0        4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625   
10     137  0.019531  0.009766  0.085938  0.019531  0.005859  0.041016   
20     296  0.011719  0.019531  0.097656  0.009766  0.003906  0.015625   
30     346  0.015625  0.023438  0.083984  0.015625  0.007812  0.013672   
40     750  0.005859  0.033203  0.072266  0.015625  0.001953  0.025391   
...    ...       ...       ...       ...       ...       ...       ...   
5890  1116  0.021484  0.021484  0.017578  0.054688  0.001953  0.017578   
5900  1230  0.031250  0.029297  0.033203  0.048828  0.001953  0.054688   
5910  1290  0.042969  0.013672  0.039062  0.035156  0.001953  0.109380   
5920  1313  0.033203  0.015625  0.023438  0.035156  0.001953  0.048828   
5930  1498  0.021484  0.015625  0.078125  0.019531  0.003906  0.044922   

       margin7   margin8   margin9  ...  texture57  texture58  texture59  \
0     0.005859  0.000000  0.005859  ...   0.015625   0.000977   0.015625   
10    0.013672  0.005859  0.000000  ...   0.020508   0.000000   0.019531   
20    0.001953  0.000000  0.005859  ...   0.005859   0.000000   0.012695   
30    0.001953  0.000000  0.007812  ...   0.019531   0.000977   0.038086   
40    0.007812  0.000000  0.005859  ...   0.017578   0.000000   0.010742   
...        ...       ...       ...  ...        ...        ...        ...   
5890  0.017578  0.000000  0.003906  ...   0.000000   0.050781   0.001953   
5900  0.017578  0.000000  0.003906  ...   0.000000   0.060547   0.000977   
5910  0.009766  0.000000  0.000000  ...   0.000000   0.033203   0.000000   
5920  0.013672  0.000000  0.000000  ...   0.000000   0.018555   0.000977   
5930  0.048828  0.000000  0.005859  ...   0.000977   0.041016   0.002930   

      texture60  texture61  texture62  texture63  texture64  Group  \
0      0.000000        0.0   0.000000   0.003906   0.053711     51   
10     0.000000        0.0   0.004883   0.013672   0.046875     51   
20     0.000000        0.0   0.004883   0.004883   0.045898     51   
30     0.000000        0.0   0.000000   0.005859   0.046875     51   
40     0.000000        0.0   0.000000   0.009766   0.041992     51   
...         ...        ...        ...        ...        ...    ...   
5890   0.005859        0.0   0.054688   0.000000   0.000000     66   
5900   0.004883        0.0   0.104490   0.000000   0.000977     66   
5910   0.004883        0.0   0.146480   0.000000   0.000000     66   
5920   0.025391        0.0   0.137700   0.000000   0.000000     66   
5930   0.035156        0.0   0.085938   0.000000   0.000000     66   

                species  
0     Quercus_Agrifolia  
10    Quercus_Agrifolia  
20    Quercus_Agrifolia  
30    Quercus_Agrifolia  
40    Quercus_Agrifolia  
...                 ...  
5890       Quercus_Ilex  
5900       Quercus_Ilex  
5910       Quercus_Ilex  
5920       Quercus_Ilex  
5930       Quercus_Ilex  

[594 rows x 195 columns]

In [123]:
predict_df.to_csv(r'D:\E\Courses\Edureka\Assignments\Dataset\Projects\pharma_test_predict.csv', index=False)

#### The CSV can be refereed for species predicted using the model.